APP_CAPTION = 'Attestaciya-PG'
APP_WIDTH = 1024
APP_HEIGHT = 768
APP_FON_NAME = 'fon.jpg'

MENU_WIDTH = 384
MENU_HEIGHT = 512
MENU_WELCOME_TITLE = 'Добро пожаловать!'
MENU_INPUT_TEXT = 'Имя: '
MENU_EXIT_TITLE = 'Выход'
MENU_NEWGAME_TITLE = 'Новая игра'

MUSIC_FILE = 'sound01.ogg'
MUSIC_STATUS = 'Музыка'
MUSIC_LEFT = 300
MUSIC_TOP = 200
MUSIC_WIDTH = MENU_WIDTH
MUSIC_HEIGHT = MENU_HEIGHT
MUSIC_STATUS_ON = 'music_on.png'
MUSIC_STATUS_OFF = 'music_off.png'

SIZE_BLOCK = 20

HEADER_MARGIN = 80

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
FRAME_COLOR = (125, 125, 255)
HEADER_COLOR = (0, 204, 153)
